# Funding Options

# GitHub Sponsors (if you set up GitHub Sponsors)
# github: vipechan

# Open Collective
# open_collective: ionova

# Custom funding links
custom: ["https://ionova.network/support", "https://discord.gg/ionova"]
