name: Security Vulnerability
description: Report a security vulnerability (PRIVATE)
title: "[Security]: "
labels: ["security", "critical"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ STOP - Read This First
        
        **DO NOT** disclose security vulnerabilities publicly in this issue tracker.
        
        Please report security vulnerabilities privately by:
        1. Emailing security@ionova.network
        2. Using GitHub's private vulnerability reporting (if enabled)
        
        See our [Security Policy](../SECURITY.md) for more details.
        
        **Bug Bounty:** We offer rewards up to $50,000 for critical vulnerabilities.
  
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm you understand the security reporting process
      options:
        - label: I understand I should report critical vulnerabilities privately
          required: true
        - label: I have read the Security Policy
          required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity (Your Assessment)
      description: How severe do you think this vulnerability is?
      options:
        - Critical - Remote code execution, data breach
        - High - Authentication bypass, privilege escalation
        - Medium - Information disclosure, DoS
        - Low - Minor security issue
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Brief description of the vulnerability (details should be sent privately)
      placeholder: General description without sensitive details...
    validations:
      required: true
  
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - Rust Node
        - Smart Contracts
        - SDK
        - Frontend/Website
        - DevNet/Docker
        - Other
    validations:
      required: true
  
  - type: checkboxes
    id: contact
    attributes:
      label: Private Reporting
      description: How will you provide the full details?
      options:
        - label: I will email full details to security@ionova.network
        - label: I will use GitHub's private vulnerability reporting
